repos:
- repo: https://github.com/pycqa/isort
  rev: 7.0.0  # matches the version in pyproject.toml
  hooks:
    - id: isort
      # No need to specify black profile as it's already in pyproject.toml
      name: isort (python)

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.0  # matches the version in pyproject.toml
  hooks:
    - id: ruff-check
    - id: ruff-format
